### ISSUE TITLE
Next player should loop

### ISSUE THREAD

**Issue by lukasvan3l** [stanRepo/real-time-web-2021#4]
https://github.com/stanRepo/real-time-web-2021/blob/main/src/socketIO/components/nextPlayerTurn.js#L7

Ik ben er niet heel diep in gedoken maar volgens mij zou je hier kunnen checken of alle spelers geweest zijn (`game.playersWhoHadTheirTurn.length === game.playersInRoom.length`) en in dat geval de lijst met players die aan de beurt zijn geweest leeg maken (`game.playersWhoHadTheirTurn = []`).

**Comment by stanRepo** [comment]
Deze methode werkt slechts gedeetelijk. Dit komt doordat wanneer de `game.playersWhoHadTheirTurn = [ ]` leeg is de speler die op dat moment aan zet is 2 maal achter elkaar geselecteerd kan worden. Ik zal elke speler een [index] waarde moeten geven waarbij ik dan kan rouleren van [1] -> [2] -> ,,,,, ,,,,, ,,,, [6] -> [1] -> [2] etc.

**Comment by stanRepo** [comment]
Op dit moment is de functionaliteit om correct over te schakelen naar de volgende speler geimplementeerd. Ook wanneer de speler die aan zet is de game verlaat zal de beurt doorgegeven worden aan de volgende speler om "stalling" te voorkomen.
