### ISSUE TITLE
Peer review all in one

### ISSUE THREAD

**Issue by NathanNeelis** [stanRepo/real-time-web-2021#5]
## Scan your buddy's repository
* [x] Does the repo have an apt description?
> Vertel in twee á drie zinnen wat jouw app is met een leuke screenshot oid.
  
> Update je beschrijving van de Repo ook even en voeg de livelink daar ook toe. 

* [x] Is there a link to the live demo at the top?
> Error op dit moment
* [x] Are any files in the repo that shouldn't be there like a .env file or node_modules?
* [x] Is there a section about the concept, install notes, data life cycle, external API, and real-time events?
> Nog even install notes toevoegen, verder zit alles erin

## Try to understand the concept
* [x] Read about the concept in the readme, do you understand what the app does?
* [x] Open up the live link (if it's already alive) and play around with the app
> Error op heroku 
* [x] Review the app's functions in an issue, feel free to add cool new ideas in an issue
> Error op heroku 
* [x] Test the app in multiple tabs, does multi-user functionality work as expected?
> Error op heroku 

## Understand the data life cycle
* [x] Are all the app's components present in a visual diagram?
* [x] Is it clear what data is stored for each component?

> Ja goede diagrammen. Zo zie je gelijk dat een spelletje maken nog best wel heel ingewikkeld is in de achtergrond.

* [x] Is it clear how components communicate with each other? (socket, polling, OAuth)
> Ja wel duidelijk. Maar je zou misschien je sockets nog even kunnen highlighten in je proces. Wanneer schakel je welk socket in, en is deze socket alleen beschikbaar in een room of ook daarbuiten? 

* [x] Can you follow where real-time data is created?
> Ja als je er doorheen leest kom je er wel uit. Maar net als mijn feedback hierboven, voor de snelle scan is het highlighten van je sockets misschien nog wel een idee.

## Check the real-time events
* [x] Are all custom events described?
> Ja heel netjes gedaan in een tabel.

* [x] Can you imagine how the client-server communication works now that you know which events are used?
> Ja, dit word door je eerste diagram heel duidelijk. 

## Review the API info
* [x] Is it clear what data the external API offers?
> Nou eigenlijk niet, maar ik weet dat je geen API gebruikt heb. Misschien handig om dit nog even toe te lichten?

* [x] Are instructions present on how to get a key from the API and how to connect to it?
> Geen API gebruikt.

**Comment by stanRepo** [comment]
Hi Nathan, bedankt voor deze uitgebreide peer review. Helaas waren er inderdaad nog wat code breaking bugs en zat ik toen nog vol in development. Ik heb al je punten verwerkt in de repo en nodig je bij deze van harte uit om samen een potje diceheads te spelen!
